---
# TODO validate asc
# https://serverfault.com/questions/896228/how-to-verify-a-file-using-an-asc-signature-file
- name: Download and install standalone binary
  get_url:
    url: "{{ borg_standalone_download_url }}"
    dest: "{{ borg_bin }}"
    owner: root
    group: root
    mode: 755
    checksum: "sha256:6338d67aad4b5cd327b25ea363e30f0ed4abc425ce2d6a597c75a67a876ef9af"
