---
- name: Vars
  include: vars.yml

- include: install.yml
  when: not borg_install_standalone_bin

- include: install_custom.yml
  when: borg_install_standalone_bin

- include: remotes.yml
- include: cron.yml
- include: prune.yml
