---

- debug:
    msg: "OS {{ ansible_distribution }}-{{ ansible_distribution_major_version }}"

- name: Include OS vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- debug: var=borg_install_standalone_bin
- debug: var=ansible_distribution

- name: Force standalone install
  set_fact:
    borg_install_standalone_bin: true
  when: (
    not borg_install_standalone_bin
    and (
      ansible_distribution == "Ubuntu"
      or (ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 30)
      or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
      or (ansible_distribution == "Debian" and ansible_distribution_major_version|int < 10)
    )
    )
